### ISSUE TITLE
DMG not available

### ISSUE THREAD

**Issue by BarnyTheGOAT** [Thinkr1/Menubar-Info#1]
recomended to make dmg available on the read me

**Comment by Thinkr1** [comment]
Sorry, this is not planned yet. Perhaps will it be available once the core functionalities have been fully completed.

**Comment by Thinkr1** [comment]
The [first release](https://github.com/Thinkr1/Menubar-Info/releases/tag/v1.0.0) is available! You can download the dmg there. Make sure to follow the installation instructions on the readme.
